"""
Django settings for indavant project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# sudo grep . 'mysite' -P -R -I -l * | xargs sed -i "s/{% mysite/{% static '/g"
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


MAIN_URL = "http://127.0.0.1:8004/"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rbktijp2tx(1e_#)7s99w=@y6xj&&3xj8ev5b9yuxd%at%+y14'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    "suit",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'loginsys',
    'news',
    'userprofile',
    "favourite",
    "notify",
    "search",
    "ckeditor",
    "endless_pagination",
    "maintenancemode",
    "nocaptcha_recaptcha",
    "password_reset",
    # "api",
    # "oauth2_provider",
    # "rest_framework",
    "rss",
    #"imagekit",
    "sorl.thumbnail",
    #"debug_toolbar",
    "django_mobile",
    "advert",
    "about",
    "beta_test",
    "reports",
)

# INTERNAL_IPS = ('127.0.0.1',)
# DEBUG_TOOLBAR_PATCH_SETTINGS = False
# DEBUG_TOOLBAR_PANELS = [
#     'debug_toolbar.panels.versions.VersionsPanel',
#     'debug_toolbar.panels.timer.TimerPanel',
#     'debug_toolbar.panels.settings.SettingsPanel',
#     'debug_toolbar.panels.headers.HeadersPanel',
#     'debug_toolbar.panels.request.RequestPanel',
#     'debug_toolbar.panels.sql.SQLPanel',
#     'debug_toolbar.panels.staticfiles.StaticFilesPanel',
#     'debug_toolbar.panels.templates.TemplatesPanel',
#     'debug_toolbar.panels.cache.CachePanel',
#     'debug_toolbar.panels.signals.SignalsPanel',
#     'debug_toolbar.panels.logging.LoggingPanel',
#     'debug_toolbar.panels.redirects.RedirectsPanel',
# ]
# CONFIG_DEFAULTS = {
#     # Toolbar options
#     'RESULTS_CACHE_SIZE': 3,
#     'SHOW_COLLAPSED': True,
#     # Panel options
#     'SQL_WARNING_THRESHOLD': 100,   # milliseconds
# }


NORECAPTCHA_SITE_KEY = "6Lc1dhMTAAAAACgdoXQlzfJSkghbnkZuONW_P3xj"
NORECAPTCHA_SECRET_KEY = "6Lc1dhMTAAAAAKjKI4WP8wmvsowHxSAyuE0isjyp"


CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',

    }
}

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_mobile.middleware.MobileDetectionMiddleware',
    'django_mobile.middleware.SetFlavourMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "maintenancemode.middleware.MaintenanceModeMiddleware",
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
    'django.middleware.locale.LocaleMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
)
MAINTENANCE_MODE = False
MAINTENANCE_URL = "503.html"
MAINTENANCE_FILE = "503.html"


ROOT_URLCONF = 'indavant.urls'


TEMPLATE_LOADERS = (
    ('django_mobile.loader.CachedLoader', (
          'django_mobile.loader.Loader',
          'django.template.loaders.filesystem.Loader',
          'django.template.loaders.app_directories.Loader',
    )),
)


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),  # Main templates
                 os.path.join(BASE_DIR, 'beta_test/templates'),  # Main templates
                 os.path.join(BASE_DIR, 'loginsys/templates'),  # Login system templates
                 os.path.join(BASE_DIR, 'news/templates'),  # News templates
                 os.path.join(BASE_DIR, 'news/mobile'),  # News templates
                 os.path.join(BASE_DIR, 'news/templatetags'),
                 os.path.join(BASE_DIR, 'userprofile/templates'),  # User profile's templates
                 os.path.join(BASE_DIR, 'favourite/templates'),  # User favourite news templates
                 os.path.join(BASE_DIR, 'notify/templates'),  # User favourite news templates
                 os.path.join(BASE_DIR, 'search/templates'),  # User favourite news templates
                 os.path.join(BASE_DIR, 'about/templates'),  # About Insydia templates
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.csrf',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.i18n',
                'django.core.context_processors.request',
                'django.core.context_processors.media',
                'django_mobile.context_processors.flavour',
            ],
        },
    },
]
from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS
TEMPLATE_CONTEXT_PROCESSORS += ('django.core.context_processors.request',)

WSGI_APPLICATION = 'indavant.wsgi.application'


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/var/tmp/django_cache',
        'TIMEOUT': 600,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}


OAUTH2_PROVIDER = {
    # this is the list of available scopes
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'}
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.ext.rest_framework.OAuth2Authentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.IsAdminUser',
    ),
    'PAGE_SIZE': 10,
}



# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'test',
        'USER': 'testuser',
        "PASSWORD": 'test',
        'HOST': '',
        'PORT': '',
        'CONN_MAX_AGE': 600,
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
# gettext = lambda s: s
LANGUAGE_CODE = 'ru-RU'
# LANGUAGES = (
#     ('ru', gettext('Russian')),
#     ('en', gettext('English')),
# )

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
if DEBUG == True:
    STATICFILES_DIRS = (
        ("static", os.path.join(BASE_DIR, 'static')),
    )
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


import json
with open(BASE_DIR+"/indavant/admin_data_mail.json") as json_file:
#with open(BASE_DIR+"indavant/admin_data_mail.json") as json_file:
    json_data = json.load(json_file)



# "static 'static/"
# static '"


# E-mail
EMAIL_USE_SSL = True
EMAIL_HOST = json_data["host"]
EMAIL_PORT = json_data["port"]
EMAIL_HOST_USER = json_data["email"]
EMAIL_HOST_PASSWORD = json_data["password"]
DEFAULT_FROM_EMAIL = json_data["email"]
DEFAULT_TO_EMAIL = DEFAULT_FROM_EMAIL
